/**
 * @typedef ServerPlayerJS
 * @type {object}
 * @prop {boolean} OP
 * @prop {boolean} alive
 * @prop {boolean} ambientCreature
 * @prop {boolean} animal
 * @prop {boolean} boss
 * @prop {boolean} child
 * @prop {boolean} creativeMode
 * @prop {boolean} crouching
 * @prop {boolean} customNameAlwaysVisible
 * @prop {boolean} elytraFlying
 * @prop {boolean} fake
 * @prop {boolean} frame
 * @prop {boolean} glowing
 * @prop {boolean} hasClientMod
 * @prop {boolean} hasCustomName
 * @prop {boolean} inWater
 * @prop {boolean} invisible
 * @prop {boolean} living
 * @prop {boolean} miningBlock
 * @prop {boolean} monster
 * @prop {boolean} noClip
 * @prop {boolean} noGravity
 * @prop {boolean} onGround
 * @prop {boolean} onLadder
 * @prop {boolean} op
 * @prop {boolean} peacefulCreature
 * @prop {boolean} player
 * @prop {boolean} silent
 * @prop {boolean} sleeping
 * @prop {boolean} spectator
 * @prop {boolean} sprinting
 * @prop {boolean} swimming
 * @prop {boolean} undead
 * @prop {boolean} underWater
 * @prop {boolean} waterCreature
 * @prop {number} absorptionAmount
 * @prop {number} airSupply
 * @prop {number} eyeHeight
 * @prop {number} fallDistance
 * @prop {number} foodLevel
 * @prop {number} health
 * @prop {number} idleTime
 * @prop {number} lastAttackedEntityTime
 * @prop {number} maxAirSupply
 * @prop {number} maxHealth
 * @prop {number} motionX
 * @prop {number} motionY
 * @prop {number} motionZ
 * @prop {number} movementSpeed
 * @prop {number} pitch
 * @prop {number} reachDistance
 * @prop {number} revengeTimer
 * @prop {number} selectedSlot
 * @prop {number} stepHeight
 * @prop {number} ticksExisted
 * @prop {number} x
 * @prop {number} xp
 * @prop {number} xpLevel
 * @prop {number} y
 * @prop {number} yaw
 * @prop {number} z
 * @prop {object} attackingEntity
 * @prop {object} block
 * @prop {object} chestArmorItem
 * @prop {object} class
 * @prop {object} customName
 * @prop {object} data
 * @prop {object} displayName
 * @prop {object} facing
 * @prop {object} feetArmorItem
 * @prop {object} fullNBT
 * @prop {object} headArmorItem
 * @prop {object} horizontalFacing
 * @prop {object} id
 * @prop {object} inventory
 * @prop {object} item
 * @prop {object} lastAttackedEntity
 * @prop {object} lastDamageSource
 * @prop {object} legsArmorItem
 * @prop {object} mainHandItem
 * @prop {ServerPlayerEntity} minecraftEntity
 * @prop {object} minecraftLivingEntity
 * @prop {object} minecraftPlayer
 * @prop {object} mouseItem
 * @prop {object} name
 * @prop {object} nbt
 * @prop {object} offHandItem
 * @prop {object} openInventory
 * @prop {object} passengers
 * @prop {object} potionEffects
 * @prop {object} profile
 * @prop {object} recursivePassengers
 * @prop {object} revengeTarget
 * @prop {object} ridingEntity
 * @prop {object} server
 * @prop {object} spawnLocation
 * @prop {object} stages
 * @prop {object} stats
 * @prop {object} tags
 * @prop {object} teamId
 * @prop {object} type
 * @prop {object} world
 * @prop {undefined} advancementDone
 * @prop {undefined} equipment
 * @prop {undefined} gameMode
 * @prop {undefined} heldItem
 * @prop {undefined} holdingInAnyHand
 * @prop {undefined} motion
 * @prop {undefined} onFire
 * @prop {undefined} onSameTeam
 * @prop {undefined} onScoreboardTeam
 * @prop {undefined} passenger
 * @prop {undefined} position
 * @prop {undefined} positionAndRotation
 * @prop {undefined} rotation
 * @prop {undefined} statusMessage
 * @prop {function} addExhaustion
 * @prop {function} addFood
 * @prop {function} addItemCooldown
 * @prop {function} addMotion
 * @prop {function} addXP
 * @prop {function} addXPLevels
 * @prop {function} attack
 * @prop {function} ban
 * @prop {function} boostElytraFlight
 * @prop {function} canEntityBeSeen
 * @prop {function} closeInventory
 * @prop {function} closeOverlay
 * @prop {function} damageEquipment
 * @prop {function} damageHeldItem
 * @prop {function} dismountRidingEntity
 * @prop {function} equals
 * @prop {function} extinguish
 * @prop {function} getAbsorptionAmount
 * @prop {function} getAirSupply
 * @prop {function} getAttackingEntity
 * @prop {function} getBlock
 * @prop {function} getChestArmorItem
 * @prop {function} getClass
 * @prop {function} getCustomName
 * @prop {function} getCustomNameAlwaysVisible
 * @prop {function} getData
 * @prop {function} getDisplayName
 * @prop {function} getEquipment
 * @prop {function} getEyeHeight
 * @prop {function} getFacing
 * @prop {function} getFallDistance
 * @prop {function} getFeetArmorItem
 * @prop {function} getFoodLevel
 * @prop {function} getFullNBT
 * @prop {function} getHasClientMod
 * @prop {function} getHasCustomName
 * @prop {function} getHeadArmorItem
 * @prop {function} getHealth
 * @prop {function} getHeldItem
 * @prop {function} getHorizontalFacing
 * @prop {function} getId
 * @prop {function} getIdleTime
 * @prop {function} getInventory
 * @prop {function} getItem
 * @prop {function} getLastAttackedEntity
 * @prop {function} getLastAttackedEntityTime
 * @prop {function} getLastDamageSource
 * @prop {function} getLegsArmorItem
 * @prop {function} getMainHandItem
 * @prop {function} getMaxAirSupply
 * @prop {function} getMaxHealth
 * @prop {function} getMotionX
 * @prop {function} getMotionY
 * @prop {function} getMotionZ
 * @prop {function} getMouseItem
 * @prop {function} getMovementSpeed
 * @prop {function} getName
 * @prop {function} getNbt
 * @prop {function} getNoClip
 * @prop {function} getNoGravity
 * @prop {function} getOffHandItem
 * @prop {function} getOpenInventory
 * @prop {function} getPassengers
 * @prop {function} getPitch
 * @prop {function} getPotionEffects
 * @prop {function} getProfile
 * @prop {function} getReachDistance
 * @prop {function} getRecursivePassengers
 * @prop {function} getRevengeTarget
 * @prop {function} getRevengeTimer
 * @prop {function} getRidingEntity
 * @prop {function} getSelectedSlot
 * @prop {function} getServer
 * @prop {function} getSpawnLocation
 * @prop {function} getStages
 * @prop {function} getStats
 * @prop {function} getStepHeight
 * @prop {function} getTags
 * @prop {function} getTeamId
 * @prop {function} getTicksExisted
 * @prop {function} getType
 * @prop {function} getWorld
 * @prop {function} getX
 * @prop {function} getXp
 * @prop {function} getXpLevel
 * @prop {function} getY
 * @prop {function} getYaw
 * @prop {function} getZ
 * @prop {function} give
 * @prop {function} giveInHand
 * @prop {function} hashCode
 * @prop {function} heal
 * @prop {function} isAdvancementDone
 * @prop {function} isAlive
 * @prop {function} isAmbientCreature
 * @prop {function} isAnimal
 * @prop {function} isBoss
 * @prop {function} isChild
 * @prop {function} isCreativeMode
 * @prop {function} isCrouching
 * @prop {function} isElytraFlying
 * @prop {function} isFake
 * @prop {function} isFrame
 * @prop {function} isGlowing
 * @prop {function} isHoldingInAnyHand
 * @prop {function} isInWater
 * @prop {function} isInvisible
 * @prop {function} isLiving
 * @prop {function} isMiningBlock
 * @prop {function} isMonster
 * @prop {function} isOP
 * @prop {function} isOnGround
 * @prop {function} isOnLadder
 * @prop {function} isOnSameTeam
 * @prop {function} isOnScoreboardTeam
 * @prop {function} isOp
 * @prop {function} isPassenger
 * @prop {function} isPeacefulCreature
 * @prop {function} isPlayer
 * @prop {function} isSilent
 * @prop {function} isSleeping
 * @prop {function} isSpectator
 * @prop {function} isSprinting
 * @prop {function} isSwimming
 * @prop {function} isUndead
 * @prop {function} isUnderWater
 * @prop {function} isWaterCreature
 * @prop {function} kick
 * @prop {function} kill
 * @prop {function} notify
 * @prop {function} notifyAll
 * @prop {function} openOverlay
 * @prop {function} playSound
 * @prop {function} rayTrace
 * @prop {function} removePassengers
 * @prop {function} revokeAdvancement
 * @prop {function} runCommand
 * @prop {function} runCommandSilent
 * @prop {function} sendData
 * @prop {function} sendInventoryUpdate
 * @prop {function} setAbsorptionAmount
 * @prop {function} setAirSupply
 * @prop {function} setChestArmorItem
 * @prop {function} setCreativeMode
 * @prop {function} setCustomName
 * @prop {function} setCustomNameAlwaysVisible
 * @prop {function} setEquipment
 * @prop {function} setFallDistance
 * @prop {function} setFeetArmorItem
 * @prop {function} setFoodLevel
 * @prop {function} setFullNBT
 * @prop {function} setGameMode
 * @prop {function} setGlowing
 * @prop {function} setHeadArmorItem
 * @prop {function} setHealth
 * @prop {function} setHeldItem
 * @prop {function} setInvisible
 * @prop {function} setLegsArmorItem
 * @prop {function} setMainHandItem
 * @prop {function} setMaxHealth
 * @prop {function} setMotion
 * @prop {function} setMotionX
 * @prop {function} setMotionY
 * @prop {function} setMotionZ
 * @prop {function} setMouseItem
 * @prop {function} setMovementSpeed
 * @prop {function} setNoClip
 * @prop {function} setNoGravity
 * @prop {function} setOffHandItem
 * @prop {function} setOnFire
 * @prop {function} setPitch
 * @prop {function} setPosition
 * @prop {function} setPositionAndRotation
 * @prop {function} setRevengeTarget
 * @prop {function} setRotation
 * @prop {function} setSelectedSlot
 * @prop {function} setSilent
 * @prop {function} setSpawnLocation
 * @prop {function} setStatusMessage
 * @prop {function} setStepHeight
 * @prop {function} setX
 * @prop {function} setXp
 * @prop {function} setXpLevel
 * @prop {function} setY
 * @prop {function} setYaw
 * @prop {function} setZ
 * @prop {function} spawn
 * @prop {function} startRiding
 * @prop {function} swingArm
 * @prop {function} tell
 * @prop {function} toString
 * @prop {function} unlockAdvancement
 * @prop {function} wait
 **/

/**
 * @typedef Entity
 * @type {object}
 * @prop {string} func_110124_au UUID
 */

/**
 * @typedef ServerPlayerEntity
 * @type {object}
 * @prop {boolean} addedToWorld
 * @prop {boolean} culledFast
 * @prop {boolean} culledShadowPass
 * @prop {boolean} culledSlow
 * @prop {boolean} dirty
 * @prop {boolean} multipartEntity
 * @prop {boolean} queryInitialized
 * @prop {boolean} queryResultDirty
 * @prop {boolean} visible
 * @prop {number} fire
 * @prop {number} query
 * @prop {object} citadelEntityData
 * @prop {object} class
 * @prop {object} dataMap
 * @prop {object} dirtyEntries
 * @prop {Entity} entity
 * @prop {object} forcedPose
 * @prop {object} language
 * @prop {object} parts
 * @prop {object} persistentData
 * @prop {object} prefixes
 * @prop {object} stages
 * @prop {object} stagesRawKJS
 * @prop {object} suffixes
 * @prop {undefined} activeItemStackUseCount
 * @prop {undefined} capability
 * @prop {undefined} classification
 * @prop {undefined} digSpeed
 * @prop {undefined} entries
 * @prop {undefined} eyeHeightAccess
 * @prop {undefined} pickedResult
 * @prop {undefined} value
 * @prop {function} an_getExperienceReward
 * @prop {function} an_shouldDropExperience
 * @prop {function} areCapsCompatible
 * @prop {function} asKJS
 * @prop {function} beCanTeleport
 * @prop {function} beGetCooldown
 * @prop {function} beGetExitPos
 * @prop {function} beResetExitPos
 * @prop {function} beSetCooldown
 * @prop {function} beSetExitPos
 * @prop {function} canBeRiddenInWater
 * @prop {function} canRiderInteract
 * @prop {function} canTrample
 * @prop {function} canUpdate
 * @prop {function} captureDrops
 * @prop {function} changeDimension
 * @prop {function} clean
 * @prop {function} curePotionEffects
 * @prop {function} deleteQuery
 * @prop {function} deserializeNBT
 * @prop {function} equals
 * @prop {function} foodEatenKJS
 * @prop {function} getCapability
 * @prop {function} getCitadelEntityData
 * @prop {function} getClass
 * @prop {function} getClassification
 * @prop {function} getDataMap
 * @prop {function} getDigSpeed
 * @prop {function} getDirtyEntries
 * @prop {function} getEntity
 * @prop {function} getEntries
 * @prop {function} getEyeHeightAccess
 * @prop {function} getFire
 * @prop {function} getForcedPose
 * @prop {function} getLanguage
 * @prop {function} getParts
 * @prop {function} getPersistentData
 * @prop {function} getPickedResult
 * @prop {function} getPrefixes
 * @prop {function} getQuery
 * @prop {function} getStages
 * @prop {function} getStagesRawKJS
 * @prop {function} getSuffixes
 * @prop {function} getValue
 * @prop {function} handler$zdp000$baseTick
 * @prop {function} handler$zdp000$changeDimension
 * @prop {function} handler$zkp001$read
 * @prop {function} hasCooldown
 * @prop {function} hashCode
 * @prop {function} initQuery
 * @prop {function} isAddedToWorld
 * @prop {function} isCulledFast
 * @prop {function} isCulledShadowPass
 * @prop {function} isCulledSlow
 * @prop {function} isDirty
 * @prop {function} isMultipartEntity
 * @prop {function} isQueryInitialized
 * @prop {function} isQueryResultDirty
 * @prop {function} isVisible
 * @prop {function} modify$zge000$_caelus_setFlag
 * @prop {function} notify
 * @prop {function} notifyAll
 * @prop {function} onAddedToWorld
 * @prop {function} onRemovedFromWorld
 * @prop {function} redirect$zjg001$elytraOverride
 * @prop {function} redirect$zjh000$eytraValidOverride
 * @prop {function} redirect$zjh002$elytraOverride
 * @prop {function} refreshDisplayName
 * @prop {function} refreshTabListName
 * @prop {function} remove
 * @prop {function} revive
 * @prop {function} serializeNBT
 * @prop {function} setActiveItemStackUseCount
 * @prop {function} setCitadelEntityData
 * @prop {function} setCulledFast
 * @prop {function} setCulledShadowPass
 * @prop {function} setCulledSlow
 * @prop {function} setDataMap
 * @prop {function} setFire
 * @prop {function} setForcedPose
 * @prop {function} setQuery
 * @prop {function} setQueryInitialized
 * @prop {function} setQueryResultDirty
 * @prop {function} setValue
 * @prop {function} shouldRiderFaceForward
 * @prop {function} shouldRiderSit
 * @prop {function} toString
 * @prop {function} wait
 * @prop {function():ResourceKeyJS} func_241141_L_ The player's spawnpoint dimension.
 * @prop {function():BlockPos} func_241140_K_ The player's spawnpoint position.
 * @prop {function():number} func_242109_L The player's spawnpoint angle.
 * @prop {function(WorldJS,number,number,boolean,boolean):Vector3d} func_242374_a The player's bed position.

 * @typedef ResourceKeyJS
 * @type {object}
 * @prop {object} class
 * @prop {object} namespace
 * @prop {object} path
 * @prop {object} registryName
 * @prop {function} compareTo
 * @prop {function} equals
 * @prop {function} getClass
 * @prop {function} getNamespace
 * @prop {function} getPath
 * @prop {function} getRegistryName
 * @prop {function} hashCode
 * @prop {function} notify
 * @prop {function} notifyAll
 * @prop {function} specialEquals
 * @prop {function} toString
 * @prop {function} wait
**/